#!/usr/bin/env node
var 
  yaml = require('yaml'), 
  fs = require('fs'),
  sys = require('sys'),
  exec = require('child_process').exec,
  cfg;

var program = require('commander');

exec('git add . > /dev/null'

git add . > /dev/null
git commit -a -m 'website update'  > /dev/null
git push > /devnull
ssh datadriven@vis4.net /home/datadriven/pull_portfolio

fs.readFile('.project', 'ascii', function(err, data) {
  if (err) {
    console.error("File could not be opened: %s", err);
    process.exit(1);
  }
  cfg = yaml.eval(data.toString('ascii'));
  console.log(cfg);
});

